### ISSUE TITLE
Native lib

### ISSUE THREAD

**Issue by FGRibreau** [igorklopov/enclose#20]
Hello !

Some natives module can't be compiled, I used `nodejs v0.12.0` and enclose without any arguments beside the app name, any idea how to solve this?

```
enclose@0.2.12
babel@4.7.16, react@0.12.2
```

``` shell
  ... some output...
  error  Cannot find module '../build/Debug/addon' from '/www/my-app/node_modules/heapdump/lib'
```

Then after removing the optional heapdump:

``` shell
  ... some output...
  error  Cannot find module 'msgpack' from '/www/my-app/node_modules/socket.io/lib/stores'
```

**Comment by igorklopov** [comment]
Added compatibility with `heapdump` and `msgpack` in enclose@0.2.14

**Comment by FGRibreau** [comment]
thanks @igorklopov, the issue with socket.io (its dependency on msgpack, `node_modules/socket.io/lib/stores/redis.js`) is as follow:

``` javascript
// packing / unpacking mechanism
  if (opts.pack) {
    this.pack = opts.pack;
    this.unpack = opts.unpack;
  } else {
    try {
      var msgpack = require('msgpack');
      this.pack = msgpack.pack;
      this.unpack = msgpack.unpack;
    } catch (e) {
      this.pack = JSON.stringify;
      this.unpack = JSON.parse;
    }
  }
```

they want require to throw if msgpack is not available so they can fallback on JSON.stringify & JSON.parse.

Redis (`node_modules/redis/index.js`) has the same issue:

``` javascript
// hiredis might not be installed
try {
    require("./lib/parser/hiredis");
    parsers.push(require("./lib/parser/hiredis"));
} catch (err) {
    if (exports.debug_mode) {
        console.warn("hiredis parser not installed.");
    }
}
```

**Comment by igorklopov** [comment]
You are right. Please try again with 0.2.15

**Comment by FGRibreau** [comment]
Hello @igorklopov,

Sadly I still have the same issue with 0.2.15:

```
/www/my-app/node_modules/my-private-module/node_modules/redis/lib/parser/hiredis.js
  error  Cannot find module 'hiredis' from '/www/my-app/node_modules/my-private-module/node_modules/redis/lib/parser'

/www/my-app/node_modules/socket.io/lib/stores/redis.js
  warning  Cannot find module 'msgpack' from '/www/my-app/node_modules/socket.io/lib/stores'
```

**Comment by igorklopov** [comment]
Lets be patient and fix the packages one by one. I added the patch for `redis`: https://github.com/igorklopov/enclose/blob/master/dictionary/redis.js Now `hiredis` absense is not an error, just a warning. So please give it another try with 0.2.16

**Comment by FGRibreau** [comment]
Ok, so now it compiles with 0.2.16 with the following output:

```

/www/my-app/node_modules/mongodb/lib/mongodb/index.js
  warning  Cannot resolve 'require('./' + path)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/mongodb/node_modules/bson/lib/bson/index.js
  warning  Cannot resolve 'require('./' + path)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/mongodb/node_modules/bson/lib/bson/index.js
  warning  Cannot resolve 'require('./' + path)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/mongodb/node_modules/bson/lib/bson/index.js
  warning  Cannot resolve 'require('./' + path)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/moment/moment.js
  warning  Cannot resolve 'require('./locale/' + name)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/heapdump/lib/main.js
  warning  Cannot find module '../build/Debug/addon' from '/www/my-app/node_modules/heapdump/lib'

/www/my-app/node_modules/heapdump/build/Release/addon.node
  warning  Cannot include native addon into executable
  The addon package must be distributed with executable

/www/my-app/node_modules/winston/lib/winston/transports.js
  warning  Cannot resolve 'require('./transports/' + transport)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/gc/node_modules/bindings/bindings.js
  warning  Cannot resolve 'require(n)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/mongodb/node_modules/bson/ext/win32/x64/bson.node
  warning  Cannot include native addon into executable
  The addon package must be distributed with executable

/www/my-app/node_modules/mongodb/node_modules/bson/build/Release/bson.node
  warning  Cannot include native addon into executable
  The addon package must be distributed with executable

/www/my-app/node_modules/mongodb/node_modules/bson/ext/win32/ia32/bson.node
  warning  Cannot include native addon into executable
  The addon package must be distributed with executable

/www/my-app/node_modules/my-private-module/node_modules/winston/lib/winston/transports.js
  warning  Cannot resolve 'require('./transports/' + transport)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/winston/node_modules/colors/lib/colors.js
  warning  Cannot resolve 'require(theme)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/winston/node_modules/colors/lib/extendStringPrototype.js
  warning  Cannot resolve 'require(theme)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/usage/lib/providers/index.js
  warning  Cannot resolve 'require("./" + providerName)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/socket.io/node_modules/socket.io-client/lib/io.js
  warning  Cannot resolve 'require('./transports/' + t)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/my-private-module/node_modules/redis/lib/parser/hiredis.js
  warning  Cannot find module 'hiredis' from '/www/my-app/node_modules/my-private-module/node_modules/redis/lib/parser'

/www/my-app/node_modules/socket.io/lib/stores/redis.js
  warning  Cannot find module 'msgpack' from '/www/my-app/node_modules/socket.io/lib/stores'

/www/my-app/node_modules/my-private-module/node_modules/winston/node_modules/colors/lib/colors.js
  warning  Cannot resolve 'require(theme)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/my-private-module/node_modules/winston/node_modules/colors/lib/extendStringPrototype.js
  warning  Cannot resolve 'require(theme)'
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option

/www/my-app/node_modules/redis/lib/parser/hiredis.js
  warning  Cannot find module 'hiredis' from '/www/my-app/node_modules/redis/lib/parser'

/www/my-app/node_modules/socket.io/node_modules/redis/lib/parser/hiredis.js
  warning  Cannot find module 'hiredis' from '/www/my-app/node_modules/socket.io/node_modules/redis/lib/parser'
```

And when I start it I get:

```
undefined:0


Error: Could not load the bindings file. Tried:
 → /www/my-app/build/gc.node
 → /www/my-app/build/Debug/gc.node
 → /www/my-app/build/Release/gc.node
 → /www/my-app/out/Debug/gc.node
 → /www/my-app/Debug/gc.node
 → /www/my-app/out/Release/gc.node
 → /www/my-app/Release/gc.node
 → /www/my-app/build/default/gc.node
 → /www/my-app/compiled/0.12.2/darwin/ia32/gc.node
    at bindings (<anonymous>)
   [... truncated ...]
```

That's because the server do a `require("gc");` on bootstrap. Where `gc` is https://github.com/siddMahen/node-gc

**Comment by FGRibreau** [comment]
@igorklopov anything I could do to help you out?

**Comment by igorklopov** [comment]
Thank you! Let me explain. Last two releases are aimed to solved your issue - step by step. I added compatibility with all modules, listed in your log: `moment`, `redis`, `usage`, `mongodb`. The last step is to make `gc()` work. It seems that https://www.npmjs.com/package/gc is outdated and does not compile against 0.12.x or 1.x. As a temporary solution you can use `--expose-gc` flag when you run compiled binary. Here is how to do it: https://gitter.im/igorklopov/enclose?at=552d3f74c46fc4bc6b358f48 Meanwhile i will try to fork `gc` package and update it.

**Comment by igorklopov** [comment]
I have forked and upgraded `gc` package. Please consider running `npm install git://github.com/igorklopov/node-gc`. Finally try EncloseJS again with your project.

**Comment by FGRibreau** [comment]
Thanks @igorklopov (and sorry for the delay!)
In fact we are using Node 0.10 so `npm install git://github.com/igorklopov/node-gc` fails:

```
  CXX(target) Release/obj.target/gc/src/gc.o
../src/gc.cc:6:23: warning: conversion from string literal to 'char *' is deprecated [-Wdeprecated-writable-strings]
        char* flags = "--expose-gc";
                      ^
../src/gc.cc:8:28: error: no member named 'RequestGarbageCollectionForTesting' in 'v8::Isolate'
        args.GetIsolate()->RequestGarbageCollectionForTesting(
        ~~~~~~~~~~~~~~~~~  ^
../src/gc.cc:9:52: error: no member named 'kMinorGarbageCollection' in 'v8::Isolate'
            args[0]->BooleanValue() ? v8::Isolate::kMinorGarbageCollection
                                      ~~~~~~~~~~~~~^
../src/gc.cc:10:52: error: no member named 'kFullGarbageCollection' in 'v8::Isolate'
                                    : v8::Isolate::kFullGarbageCollection);
                                      ~~~~~~~~~~~~~^
../src/gc.cc:11:9: error: use of undeclared identifier 'scope'
        NanReturnValue(NanUndefined());
        ^
../node_modules/nan/nan.h:835:39: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return scope.Close(value)
                                      ^
1 warning and 4 errors generated.
make: *** [Release/obj.target/gc/src/gc.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/fg/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 12.6.0
```

We use the heapdump module that fails too, however if I remove both gc & heapdump everything worked fine!

**Comment by serkanp** [comment]
i have problem with native modules.. such as sqlite3
my app.js:
var fs=require('fs')
var path=require('path')
console.log(path.resolve(__dirname))
var moment=require('moment')
console.log(moment().format())
console.log('try loading sqlite3')
try {
require.resolve("sqlite3");
} catch(error) {
console.log("Failed to require('sqlite3')");
console.log("Please run 'npm install' here");
process.exit(1);
}

console.log('seems sqlite can be loaded')

var sqlite=require('sqlite3')

my package.json:
{
"name": "deneme",
"version": "1.0.0",
"description": "",
"main": "index.js",
"dependencies": {
"moment": "^2.10.2",
"sqlite3": "^3.0.5"
},
"devDependencies": {
"moment": "^2.10.2",
"sqlite3": "^3.0.5"
},
"scripts": {
"test": "echo \"Error: no test specified\" && exit 1"
},
"author": "",
"license": "ISC"
}

enclose output:
E:\deneme>enclose --x64 app.js

e:\deneme\node_modules\sqlite3\lib\sqlite3.js
warning Cannot resolve 'require(binding_path)'
Use a string literal as argument for 'require', or leave it
as is and specify the resolved file name in 'scripts' option

e:\deneme\node_modules\moment\moment.js
warning Cannot resolve 'require('./locale/' + name)'
Use a string literal as argument for 'require', or leave it
as is and specify the resolved file name in 'scripts' option

e:\deneme\node_modules\sqlite3\node_modules\node-pre-gyp\lib\node-pre-gyp.js
warning Cannot resolve 'require('./' + command)'
Use a string literal as argument for 'require', or leave it
as is and specify the resolved file name in 'scripts' option

e:\deneme\node_modules\sqlite3\node_modules\node-pre-gyp\lib\node-pre-gyp.js
warning Cannot resolve 'require('./' + c)'
Use a string literal as argument for 'require', or leave it
as is and specify the resolved file name in 'scripts' option

e:\deneme\node_modules\sqlite3\node_modules\node-pre-gyp\lib\pre-binding.js
warning Cannot resolve 'require(package_json_path)'
Use a string literal as argument for 'require', or leave it
as is and specify the resolved file name in 'scripts' option

i get this when i run app.exe:
E:\deneme>app.exe
e:\thebox\deneme
2015-04-26T23:26:47+03:00
try loading sqlite3
seems sqlite can be loaded
undefined:0

Error: Cannot find module 'e:\thebox\deneme\node_modules\sqlite3\lib\binding\nod
e-v14-win32-x64\node_sqlite3.node'
at Error (native)
at O ()
at c ()
at Object.Math.Enclose.+e+:++t+h+e+b+o+x++d+e+n+e+m+e++n+o+d+e+_+m+o+d+u+
l+e+s++s+q+l+i+t+e+3++l+i+b++s+q+l+i+t+e+3+.+j+s.dev ()
at u ()
at O ()
at c ()
at Object.Math.Enclose.+e+:++t+h+e+b+o+x++d+e+n+e+m+e++a+p+p+.+j+s.dev (<
anonymous>)
at u ()
at

**Comment by igorklopov** [comment]
@FGRibreau Great!
About `gc` and `heapdump`. EncloseJS has node 0.12 inside. This means that your compiled project will run in 0.12 environment regardless of your 0.10 installed in system. Hence, the problem is only that you can not make 0.12-compatible native modules if you have 0.10 installed. Soon i will find a good solution.

**Comment by FGRibreau** [comment]
@igorklopov ok, this app is good now, awesome!

Now the next app: 

``` javascript
/www/my-app/node_modules/connect-mongodb/node_modules/connect/lib/middleware/compiler.js
  error  Cannot find module 'sass' from '/www/my-app/node_modules/connect-mongodb/node_modules/connect/lib/middleware'

/www/my-app/node_modules/connect-mongodb/node_modules/connect/lib/middleware/compiler.js
  error  Cannot find module 'less' from '/www/my-app/node_modules/connect-mongodb/node_modules/connect/lib/middleware'

/www/my-app/node_modules/connect-mongodb/node_modules/connect/lib/middleware/compiler.js
  error  Cannot find module 'coffee-script' from '/www/my-app/node_modules/connect-mongodb/node_modules/connect/lib/middleware'
```

**Comment by serkanp** [comment]
@igorklopov hi , 
how can i use enclosejs in arm cpu.. ?
i need to compile my app in cubieboard and raspberry pi.. (armv6 or armv7)
i need the hardfp compilation :))
you only put :
function get_suffix(arch) {
  return {
    win32: {
      x86: "win32",
      x64: "win64"
    },
    linux: {
      x86: "linux-x86",
      x64: "linux-x64"
    },
    darwin: {
      x86: "darwin-x86",
      x64: "darwin-x64"
    }
  }[process.platform][arch];
}

**Comment by igorklopov** [comment]
@serkanp i dont have ARM-based board, but i signed up to scaleway.com. they have:

```
root@scw-16d18f:~# uname -a
Linux scw-16d18f 3.2.34-29 #16 SMP Thu Mar 12 09:45:43 UTC 2015 armv7l armv7l armv7l GNU/Linux
```

i hope i will compile what you need. i will post here when i have an ARM port

**Comment by igorklopov** [comment]
```
root@scw-16d18f:~# cat /proc/cpuinfo
Processor       : Marvell PJ4Bv7 Processor rev 2 (v7l)
processor       : 0
BogoMIPS        : 1332.01
processor       : 1
BogoMIPS        : 1332.01
processor       : 2
BogoMIPS        : 1332.01
processor       : 3
BogoMIPS        : 1332.01
Features        : swp half thumb fastmult vfp edsp vfpv3 tls
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x584
CPU revision    : 2
Hardware        : Online Labs C1
Revision        : 0000
Serial          : 0000000000000000
```

**Comment by serkanp** [comment]
@igorklopov  you can use qemu to virtualize the arm cpu and os.. 
check https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=37386

**Comment by serkanp** [comment]
also if you want i can provide you an arm hardware with remote access.. you can do whatever you like..

**Comment by serkanp** [comment]
any update? :)

**Comment by igorklopov** [comment]
@FGRibreau I fixed `connect-mongodb` in enclosejs 0.2.22. Please try again.

**Comment by FGRibreau** [comment]
@igorklopov thanks ! Now the issue is:

``` shell
/www/my-app/node_modules/jade/index.js
  error  Cannot find module './lib-cov/jade' from '/www/my-app/node_modules/jade'
```

**Comment by igorklopov** [comment]
You seem to use old jade (1.1.5 or lower). `lib-cov` was removed in 1.2.0. Can you update to latest version and try again? https://github.com/jadejs/jade/blob/master/History.md

**Comment by serkanp** [comment]
igor your mail address gives :
Delivery to the following recipient failed permanently:

```
 igor@klopov.com
```

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain klopov.com by mx4.masterhost.ru. [83.222.23.173].

The error that the other server returned was:
550 rejected because relaying is not allowed

:)) do we have any update?

**Comment by igorklopov** [comment]
@serkanp Yes. Please try again with 0.2.27

**Comment by serkanp** [comment]
arm version works perfect,, thanks for the hard work bro.. 

i have one more question :))
on arm raspberry pi , the application starts very slowly and delayed..5-10 second startup (starts very fast when directly run with nodejs itself, under 1 second)
do you have any idea for it?

**Comment by igorklopov** [comment]
You are welcome, Serkan!

In enclosed state the app loads all js code of the project into memory at start. When run with nodejs - not all js files are `require`d. I will make a research here. Also, one of future improvements will probably solve this issue.

**Comment by julian-weinert** [comment]
@igorklopov can I also compile for ARM on a x86 based computer? Or generally for foreign platforms?
